### ISSUE TITLE
Calculate SnR in Controller

### ISSUE THREAD

**Issue by JeroenDoornbos** [IvoVellekoop/openwfs#10]
The function 'compute_transmission' currently only returns the transmission matrix, but should also return the SnR of each element.

**Comment by IvoVellekoop** [comment]
Implemented and documented in:
Mastiani, Bahareh, Daniël WS Cox, and Ivo M. Vellekoop. "Practical considerations for high-fidelity wavefront shaping experiments." Journal of Physics: Photonics 6.3 (2024): 033003.
