### ISSUE TITLE
Embed python in 3rdpartypublic subrepo of Micro-Manager 

### ISSUE THREAD

**Issue by JeroenDoornbos** [IvoVellekoop/openwfs#18]

**Comment by IvoVellekoop** [comment]
This should not be necessary anymore. The plugin now locates the python3.dll using the standard windows dll search strategy (searching in system32 and the folders specified by the PATH environment variables). If Python is on the path (i.e. can be run from the command prompt), that install is automatically used. If no Python is installed, the plugin appears inactive in the MM plugin list and cannot be loaded, which seems to be sensible behavior.
