### ISSUE TITLE
Generic Fourier-based WFS needs to support multi-dimentional feedback

### ISSUE THREAD

**Issue by JeroenDoornbos** [IvoVellekoop/openwfs#21]

**Comment by JeroenDoornbos** [comment]
As in StepwiseSequential, the basic FourierDualRef implementation needs to be able to handle feedback of larger arrays than [1]. The returned Fourier transformation matrices need to be of shape [k_x,k_y,feedback_elements], and the computation of a pupil plane transformation matrix needs to be done by selecting a (or multiple) specific feedback element(s) (As it can be quite a heavy computation)

**Comment by IvoVellekoop** [comment]
FourierDualRef now supports multi-target feedback (in non-iterative mode). The returned matrices are still full [b, y, x], with b the target number, and x and y pixel positions. A compressed representation (only storing mode indices [b, k_x, k_y] may be added later
