### ISSUE TITLE
Create a Fourier algorithm that does not have a pupil overlap

### ISSUE THREAD

**Issue by JeroenDoornbos** [IvoVellekoop/openwfs#24]
Theoretically, measuring the 0th order mode (phasestepping the flat field of one pupil while holding the other the same) should already give you enough information to correct for their individual offsets. We know the efficiency of the algorithm is highest for an overlap of 0. 

Therefore, we should develop a new algorithm that uses those 0th order measurements to calculate the relative phase between the two pupils, and perhaps replace the current Fourier base class implementation using this.

**Comment by IvoVellekoop** [comment]
The FourierDualRef (and other DualReference algorithms) no longer need overlap.
