### ISSUE TITLE
continously generating random data when calling read()

### ISSUE THREAD

**Issue by jacopoabramo** [IvoVellekoop/openwfs#32]
I'm writing a small example where I'm using Qt widgets to continously capture images from a source and show them into an image viewer. Right now the image is always the same, most probably because the source is StaticSource, but I would like to simulate something that is more realistic. I know that there are some simulators for SLM but I would like to start with something simpler, like an iSCAT PSF or a TIRF channel where some particles are in the FoV. Do you have any suggestions for that?

I also would like to drive the simulated actuators in order to move the image in the FoV. I saw that the Camera has built-in support for that, I just need to make the widgets and connect them to the synthetic generator but I wanted to solve the generation issue first.

Here's the example below (just remove the .txt extension to make it work)

[continous_example.py.txt](https://github.com/user-attachments/files/18004410/continous_example.py.txt)

There are some requirements to install

```
ndv[pyside,vispy]
psygnal
qtpy
```

If it's of some interest I can make a PR and add this to the examples folder.

**Comment by jacopoabramo** [comment]
I just realized that although declared as a static source there's a bit of change in the displayed data which somewhat resembles what I'm trying to do. I'll make a simulated movement to confirm then if it works I'll just close the issue.

**Comment by IvoVellekoop** [comment]
Hi Jacopo,

The camera object can simulate shot noise and additive Gaussian noise, which is sufficient for our own purposes. If you need it, you could extend the noise model of the Camera object, implement a new Processor that adds noise, or extend the NoiseSource with a new noise model. Currently it only supports uniform and Gaussian, but it is very straightforward to add other modalities.
If you want to move the sample, you can use the stage of the Microscope object. The Camera object itself does not have actuators

Ivo 

P. S. I could not run the example. The NDArray() object first gave me the error that the data was missing, and now gives me a "no canvas backend found".

**Comment by jacopoabramo** [comment]
I just realized that I cheated a bit and I'm working with a more recent version of ndv from it's main branch, so that could be why it's not working. I'll test it out on my side and let you know.

**Comment by jacopoabramo** [comment]
Yeah... the version currently released on pypi of ndv doesn't support this kind of behavior I'm proposing. I'll close the issue since I know understand the problem so it's something I can configure/adapt to my use case.

If you still would like to give it a shot in trying it, you can install the latest branch of ndv with this code:

[continous_example.py.txt](https://github.com/user-attachments/files/18005792/continous_example.py.txt)

```
latest branch of ndv[pyqt,vispy]
psygnal
qtpy
```

And try again. Once a new release is published that supports this script I'll make a PR and add it to the examples.
